### PR TITLE
fix [#77] : Ask confirmation on reset

### PR DESCRIPTION
**Pull request by ADISKING1**
### Fixes #77
Added an "Are you sure" dialog to Suitcase App, that briefly explains what is about to happen.

### CODE REVIEW

**Comment by linl33** [comment]
runtests

**Comment by wbrunette** [comment]
fixes odk-x/tool-suite-X#77

**Review by linl33 — APPROVED** [review]

**Comment by ADISKING1** [comment]
Thank you for reviewing my work!
You can let me know if you need something added or modified.

**Review by wbrunette — APPROVED** [review]

**Comment by wbrunette** [comment]
Closes: https://github.com/odk-x/tool-suite-X/issues/77

**Pull request merged**
