### PR TITLE
Add odk-x logo to login page

### PR DESCRIPTION
**Pull request by Shubhamr837**
Whats included in this PR?
Add odk-x logo to login panel 
Screenshot :
Screenshot from 2021-06-07 14-43-39 Cropped

### CODE REVIEW

**Comment by linl33** [comment]
runtests

**Comment by linl33** [comment]
Replaces odk-x/suitcase#63

**Review by linl33 — CHANGES_REQUESTED** [review]
Overall the functionality looks good. Just a few small things to change.

The left margin on the login screen is significantly larger than the right margin. If you could make the 2 margins the same size that would be great. Not a big issue though so if it ends up taking too much time than it's fine as it is.

**Comment by Shubhamr837** [comment]
Thanks for the review @linl33 .I have implemented the changes. After removing extra space from the left, I also reduced the weightx of logo to 20 from 25 as there was less space needed for the logo.

**Comment by linl33** [comment]
runtests

**Review by linl33 — APPROVED** [review]

**Pull request merged**
