### PR TITLE
Update Suitcase UI (GSOC 2021 Project)

### PR DESCRIPTION
**Pull request by wbrunette**
@Shubhamr837's successful GSOC 2021 Project

### CODE REVIEW

**Comment by wbrunette** [comment]
@Shubhamr837 for the tests to pass we need to add the assertj-swing-aut jar. You mentioned you did a local install of the jar which is fine but we need to add the jar to the dependencies folder so we can automate the process like we do with the mvn_local_install as you mentioned.

@Shubhamr837 mentioned this in https://github.com/odk-x/suitcase/pull/65 but we need the jar so we can add to the dependencies. Where can we get the jar?

**Comment by Shubhamr837** [comment]
Sorry for being late , @wbrunette the jar file is in the github repo https://github.com/assertj/assertj-examples/tree/main/assertj-swing-aut . I built the jar in my local system. I have created the pull request to add the jar file.

**Comment by wbrunette** [comment]
@Shubhamr837 I merged you PR with the JAR and fixed a previous merge problem. We are now getting a version problem. 

[ERROR]   bad class file: C:\Users\waylon\.m2\repository\com\github\caciocavallosilano\cacio-tta\1.11\cacio-tta-1.11.jar(com/github/caciocavallosilano/cacio/ctc/junit/CacioTestRunner.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.

From the error message, I guessing it is likely a Java version problem. Please checkout the "gsoc-2021" branch and try and compile it with Java 8.

This is one of the last things I want to include in the upcoming 2.1.9 release

**Comment by wbrunette** [comment]
@Shubhamr837 any updates?

**Comment by Shubhamr837** [comment]
@wbrunette I have recreated the error, there is a problem with assertj java version. I am trying to solve this.

**Comment by Shubhamr837** [comment]
@wbrunette I have solved the problem locally. I changed the version of com.github.caciocavallosilano in pom.xml to 1.10 and the application compiled and ran successfully. I have created a pull request for that. Please have a look again and inform me if any other error occurs.

**Comment by wbrunette** [comment]
runtests

**Pull request merged**
